title: Yuto Yokoyama
description: Yuto Yokoyama Personal website
url: "https://yuto-yokoyama.github.io"
baseurl: ""

remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
  # - jekyll-feed

minima:
  skin: auto
  nav_pages:
    - index.md
    - news.md
    - publications.md
    - presentations.md
    - cv.md

author:
name: Yuto Yokoyama

social_links:

title: researchmap
icon: link
url: https://researchmap.jp/YutoYokoyama
title: Google Scholar
icon: link
url: https://scholar.google.com/citations?user=DpeS1JAAAAAJ&hl=en
